spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mentoring_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: mentoring
